### ISSUE TITLE
A way to access errors for fields not in the schema when using `errorMessagesForSchema`

### ISSUE THREAD

**Issue by danielweinmann** [SeasonedSoftware/domain-functions#51]
Scenario with Remix Forms, let's say we're updating a user at `/users/$userId/edit`:

```tsx
const formSchema = z.object({
  firstName: z.string().min(1),
  email: z.string().min(1).email(),
})

const mutationSchema = formSchema.extend({ userId: z.string() })

const mutation = makeDomainFunction(mutationSchema)(async (values) => values)

export const action: ActionFunction = async ({ request, params }) =>
  formAction({
    request,
    schema,
    mutation,
    transformValues: (values) => ({ ...params, ...values }),
  })

export default () => <Form schema={formSchema} />
```

If for any reason the `userId` is not present in the params, the `mutation` will not succeed but `formAction` will not return an error for the missing userId because it is [using errorMessagesForSchema under the hood](https://github.com/SeasonedSoftware/remix-forms/blob/main/packages/remix-forms/src/mutations.ts#L79).

It would be nice if we could access those errors that are not part of the schema. Either as part of the return value of `errorMessagesForSchema` or through another helper function.

That way Remix Forms could show them as global errors and give feedback to the developer that something is off with the wiring between Form and action. Right now, the form submission will not succeed but no error will be shown.

**Comment by danielweinmann** [comment]
If I'm understanding your suggestion, before we [call the mutation](https://github.com/SeasonedSoftware/remix-forms/blob/main/packages/remix-forms/src/mutations.ts#L71), we would compose it with mapError and extract the errors manually, correct?

If that's what you mean, it would defeat the purpose of using `errorMessagesForSchema` since to know what's _not_ part of the schema, we'd have to do what errorMessagesForSchema does manually.

Am I missing something?

**Comment by danielweinmann** [comment]
Related issue on Remix Forms: https://github.com/SeasonedSoftware/remix-forms/issues/130

**Comment by diogob** [comment]
would something like this work?
```ts
const formSchema = z.object({
  firstName: z.string().min(1),
  email: z.string().min(1).email(),
})

const mutationSchema = formSchema.extend({ userId: z.string() })

const makeUserIdErrorsGlobal = (e) => {
  const userIdError = e.inputErrors.find((iErr) => iErr.path = ['userId'])
  return {...e, errors: [...e.errors, { message: 'Error in userId: ' + userIdError.message }] }
}

const mutation = mapeError(makeDomainFunction(mutationSchema)(async (values) => values), makeUserIdErrorsGlobal)

export const action: ActionFunction = async ({ request, params }) =>
  formAction({
    request,
    schema,
    mutation,
    transformValues: (values) => ({ ...params, ...values }),
  })

export default () => <Form schema={formSchema} />
```

**Comment by diogob** [comment]
another possible solution is to use the DF environment to pass `userId`.

**Comment by diogob** [comment]
In that case it seems easier to implement a change in remix-forms, since the form has access to the schema.
